const NOTIFICATION_ACTIONS = {
  LOGIN_USER: "LOGIN_USER",
  VOTER: {
    CREATE: "CREATE_VOTER",
    UPDATE: "UPDATE_VOTER",
    DELETE: "DELETE_VOTER",
    FETCH_ALL: "FETCH_ALL_VOTERS",
  },
  COMPETITION: {
    CREATE: "CREATE_COMPETITION",
    UPDATE: "UPDATE_COMPETITION",
    DELETE: "DELETE_COMPETITION",
    FETCH_ALL: "FETCH_ALL_COMPETITIONS",
  },
  CATEGORY: {
    CREATE: "CREATE_CATEGORY",
    UPDATE: "UPDATE_CATEGORY",
    DELETE: "DELETE_CATEGORY",
    FETCH_ALL: "FETCH_ALL_CATEGORIES",
  },
  PARTICIPANT: {
    FETCH_ALL: "FETCH_ALL_PARTICIPANTS",
    CREATE: "CREATE_PARTICIPANT",
  },
};

const DEFAULT_OPTIONS = {
  vertical: "bottom",
  horizontal: "center",
  openNotification: false,
  autoHideDuration: 5000,
};

const NOTIFICATION_SEVERITY = {
  error: "error",
  warning: "warning",
  info: "info",
  success: "success",
};

export { NOTIFICATION_ACTIONS, DEFAULT_OPTIONS, NOTIFICATION_SEVERITY };
