const PARTICIPANT_ACTIONS = {
  CAST_VOTE: "CAST_VOTE",
  UNDO_VOTE: "UNDO_VOTE",
  SHOW_PARTICIPANTS: "SHOW_CATEGORY_PARTICIPANTS",
  HIDE_PARTICIPANTS: "HIDE_CATEGORY_PARTICIPANTS",
};

const CATEGORY_ACTIONS = {
  SELECT_CATEGORY: "SELECT_CATEGORY",
};

export { PARTICIPANT_ACTIONS, CATEGORY_ACTIONS };
